---
title: "Data delivery"
author: "Willem Goossens"
date: "2025-11-19"
output: html_document
---

File based on the complete dataset downloaded.
We filter that data here, based on location, space and pollinator species

# START
```{r}
rm(list=ls())
```


```{r}
library(tidyverse)
library(sf)
```

# OBSERVATION
## 1 LOAD
```{r}
obs <- read_csv("../Data/Observation/observation_org_hymenoptera_1995_2025.csv")
```

## 2 FILTER
## 2.1 Filter
```{r}
# remove uncertain 
length(obs$id[obs$`is certain`==FALSE])
obs <- obs[obs$`is certain`==TRUE,]

# remove obscure
length(obs$id[obs$obscurity =="1"])
obs <- obs[obs$obscurity=="0",]

# check how many have pictures
sum(obs$`has photos`, na.rm=T)
```


## 2.2 Space
```{r}
# only get european countries
europe <- c(
  "Albania", "Andorra", "Austria", 
  "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria",
  "Croatia", "Cyprus", "Czechia", 
  "Denmark", 
  "Estonia",
  "Finland", "France",
   "Germany", "Greece",
  "Hungary",
  "Iceland", "Ireland", "Italy",
  "Kosovo", 
  "Latvia", "Liechtenstein", "Lithuania", "Luxembourg",
  "Malta", "Moldova", "Monaco", "Montenegro",
  "Netherlands", "North Macedonia", "Norway",
  "Poland", "Portugal",
  "Romania", 
  "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain","Sweden", "Switzerland",
  "Ukraine", "United Kingdom", 
  "Vatican City")

# retrieve --> these are by far the most species
obs <- obs[obs$country %in% europe,]

# check regions
regions <- obs |> group_by(country) |> summarise(n=n())

# check accuracy
# how many remove if accuracy not more than 250 m
length(obs$accuracy[obs$accuracy >250])
sum(is.na(obs$accuracy))
# 1,000,000
# remove all observations with higher uncertainty
obs <- obs[!obs$accuracy>250 ,]

# check whether all observations have coordinates
obs <- obs[!is.na(obs$lat) | !is.na(obs$lng),]
```


```{r}
# to plot
# Convert coordinates to sf points
# coord <- obs[, c("id", "lat", "lng")] %>% st_as_sf(coords = c("lng", "lat"), crs = 4326)
# ggplot()+ geom_sf(data= coord)

```

## 2.3 Time
```{r}
# make date a date type
obs$date <- as.Date(obs$date)

# check spreak
hist(obs$date, breaks= "years")
# between 14 februari 1995 and 18 november 2025
min(obs$date)
max(obs$date)
# 50% of observations last 2 years
median(obs$date)
```


## 2.3 Species
```{r}
# quick subdivision here
obs2 <- obs[obs$`has photos`==TRUE,]
obs3 <- obs[obs$`has photos`== FALSE & !is.na(obs$`related species`),]

# only get pollinators
families <- obs |> group_by(family) |> summarise(n= n())
writeClipboard(families$family)
# these are the bee families
bees <- c( "Andrenidae", "Apidae", "Colletidae","Halictidae","Megachilidae","Melittidae")
wasps <- c("Scoliidae", "Thynnidae", "Tiphiidae","Vespidae","Pompilidae","Sphecidae", "Crabronidae","Masaridae", "Sapygidae")
extra <- c("Apoidea", "Anthophila", "Apocrita")


# how many observations are from bees
sum(families$n[families$family%in% bees | families$family%in% wasps | families$family%in% extra])
sum(families$n[families$family%in% bees])
# 2,611,205 (with wasps 3,626,149)
# if pictures 1,8225,524 (with wasps 2,624,720)
# if only indication 181,223 (with wasps 189.030)


# here a very brief check of all species names
# you can change obs to 2 or 3 to check what difference this would make for the final dataset
names <- obs |> group_by(`scientific name`, `species type`) |> summarise(n = n())

# check how many are aggregates
sum(names$n[names$`species type`=="aggregate species"])
sum(names$n[names$`species type`!="aggregate species"])
```

```{r}
# only save relevant columns
col_save <- c("id","date","time","species name","scientific name","family","species type","number","sex","life stage","activity",
              "related species","related species name","lat","lng","accuracy","country","validation status","has photos", "link")
# retrieve these columns
obs <- obs[, colnames(obs) %in% col_save]

# check number of observations with related species
length(obs$id[!is.na(obs$`related species`)])
# 525,980 observations
# and 217,000 of these have no image
# 300,000 can be used for validation normally 
# but it should still be checked whether these are all pollinators

obs <- obs[obs$family %in% bees,]

# remove rejected
obs <- obs[!obs$`validation status` == "rejected", ]
```


## 2.4 Euromed
```{r}
# merge with euro_med regions
# reduce dataset
coord <- obs |> dplyr::select("id", "country","lat", "lng")
colnames(coord)[2] <- "observation_country"

# make geometrical dataset
coord <- st_as_sf(coord, coords = c("lng","lat"),crs = 4326)

# check regions
medRegions <- read_sf("~/Doctoraat/Impact/Extra data/EURO+MED/Regions", "Emed_regions")
medRegions <- st_transform(medRegions, CRS("+proj=longlat +datum=WGS84"))

# Assign all plots which are within one of the regions to the given region
sf_use_s2(T) #S2 can provide better performance for certain types of spatial operations, especially when dealing with large spatial datasets.
joinedData <- st_join(coord, medRegions[-20,], join = st_within)

# There is something awry with the geometry of the Netherlands, this is why we treat it specially here
sf_use_s2(F)
res <- st_join(coord, medRegions[20,], join = st_within)
# Merge the Netherlands back into the overall data
# use the in data to give the index for joinedData (because we use res for the region and replace totally with the subset of data being from the Netherlands)
joinedData[(res$Region == "Netherlands") %in% TRUE,] <- res[(res$Region == "Netherlands") %in% TRUE,]
sf_use_s2(T)

# check how many not assigned
sum(is.na(joinedData$Region))/nrow(joinedData)
```



Change some names
```{r}
# give the points without a country their region
joinedData$country[is.na(joinedData$country)] <- joinedData$Region[is.na(joinedData$country)]
```


Assign remaining
```{r}
# which plots are not assigned, many of them are located near the coast
remainingPlots <- joinedData[is.na(joinedData$country),]
# assign all to closest region
remainingPlots <- st_join(remainingPlots[, 1:2], medRegions[-20,], join = st_nearest_feature)

# for Netherlands, check again
# There is something awry with the geometry of the Netherlands, this is why we treat it specially here
sf_use_s2(F)
res <- st_join(remainingPlots[remainingPlots$observation_country=="Netherlands", 1:2], medRegions[20,], join = st_nearest_feature)
# Merge the Netherlands back into the overall data
# use the in data to give the index for joinedData (because we use res for the region and replace totally with the subset of data being from the Netherlands)
remainingPlots[(remainingPlots$observation_country == "Netherlands") %in% TRUE,] <- res[(res$Region == "Netherlands") %in% TRUE,]
sf_use_s2(T)

# assign again
joinedData[is.na(joinedData$country),] <- remainingPlots
```


```{r}
# give the points without a country their region
joinedData$country[is.na(joinedData$country)] <- joinedData$Region[is.na(joinedData$country)]

# change United Kingdom
joinedData$country <- gsub("United.Kingdom","United Kingdom",joinedData$country)
joinedData$country <- gsub("Republic.of.Ireland","Ireland",joinedData$country)
countries <- unique(joinedData$country)

# check whether the number of countries and regions is the same
sum(is.na(joinedData$country)) == sum(is.na(joinedData$Region))

# change to Sicily
joinedData$country[joinedData$country %in% "Italy & Malta"] <- joinedData$Region[joinedData$country %in% "Italy & Malta"]
# change to Turkey 
joinedData$country[joinedData$country %in% "Greece & Turkey"] <- "Greece"
```


Check overlap countries and Euro+MED
```{r}
# how many are the same
sum(joinedData$observation_country == joinedData$country)/length(joinedData$id)

# which not
remaining <- joinedData[joinedData$observation_country != joinedData$country, ]

# plot data to check
#ggplot()+ geom_sf(data= remaining) +geom_sf(data = medRegions, fill = NA, color = "grey", size = 0.2, alpha= 0.5)

# create box around Europe
europe_bbox <- st_bbox(c(xmin = -30, xmax = 80, ymin = 20, ymax = 90))
europe_polygon <- st_as_sfc(europe_bbox)

# crop to regions
sf_use_s2(F)
joinedData_mainland <- st_crop(joinedData, europe_polygon)
joinedData_mainland <- st_crop(joinedData_mainland, medRegions, crop=F)
sf_use_s2(T)

# remove some
removed <- joinedData[!joinedData$id %in% joinedData_mainland$id,] 
joinedData <- joinedData_mainland
obs <- obs[obs$id %in% joinedData$id, ]

# plot the removed ones
ggplot()+ geom_sf(data= removed) +geom_sf(data = medRegions, fill = NA, color = "grey", size = 0.2, alpha= 0.5)

# we will use our own classication to align with iNaturalist
obs$euromed_region <- joinedData$country[match(obs$id, joinedData$id)]
```



## 3 SAVE
```{r}
# save
write_csv(obs, "../Data/Observation/observation_org_bees.csv")

# most observations have pictures
# remove observations that have neither a picture nor an associated (related) species
pol_indicated <- obs[obs$`has photos`== FALSE & !is.na(obs$`related species`),]
nrow(pol_indicated)
# how many observations are useless
nrow(obs[obs$`has photos`== FALSE & is.na(obs$`related species`),])
# the following code also retrieve only those with a picture, but that is not really required
# we just save obs altogether and can then later clean the data further if required
obs2 <- obs[obs$`has photos`==TRUE,]
nrow(obs[obs$`has photos`==TRUE,])
```

