---
title: "Preparation Observation.org"
author: "Willem Goossens"
date: "2025-11-26"
output: html_document
---

Clean names

# START
```{r}
rm(list=ls())
```


```{r}
library(tidyverse)
library(sf)
library(rgbif)
library(kewr)
```

# OBSERVATION
## 1 LOAD
```{r}
obs <- read_csv("../Data/Observation/observation_org_bees.csv",show_col_types = FALSE)
```

## 2 NAMES
## 2.1 Types cleaning
```{r}
# check species names per type
names <- obs |> group_by(`scientific name`, `species name`,`species type`) |> summarise(n = n())
# quite some of them are aggregated groups
# how will we deal with this

# what types are there
unique(names$`species type`)

# check how many are not species
sum(names$n[names$`species type`=="species"])/sum(names$n)
sum(names$n[names$`species type`=="aggregate species"])/sum(names$n)
# about 20% if observation are not species, 18% of which are aggregates

# get all species observations
names$name <- NA
names$type <- NA
names$type[names$`species type`=="species"] <- "Species"
names$name[names$`species type`=="species"] <- names$`scientific name`[names$`species type`=="species"]

# get varieties
names$type[names$`species type`=="variety"] <- "Variety"
names$name[names$`species type`=="variety"] <- names$`scientific name`[names$`species type`=="variety"]

# get synonyms
names$type[names$`species type`=="synonym"] <- "Synonym"
# change synonyms
names$name[names$`species type`=="synonym"] <- c("Andrena pelagica","Lasioglossum (Dialictus) spec.", "Eoanthidium anale",
                                                 "Eucera nigrescens","Eucera proxima","Eucera longicornis","Megachile salsburyana",
                                                 "Tetralonia iberica")

# get 'forma'
names$type[names$`species type`=="forma"] <- "Forma"
names$name[names$`species type`=="forma"] <- c("Andrena trimmerana")

# get subspecies
names$type[names$`species type`=="subspecies"] <- "Subspecies"
names$name[names$`species type`=="subspecies"] <- names$`scientific name`[names$`species type`=="subspecies"]


# Now we will start to look at the aggregate species
# get all genus level observations
names$type[grepl("spec.", names$`scientific name`)] <- "Genus"
names$name[grepl("spec.", names$`scientific name`)] <-  gsub(" spec.", "", names$`scientific name`[grepl("spec.", names$`scientific name`)])
names$name[grepl( ")$", names$name)] <- sapply(strsplit(names$name[grepl( ")$", names$name)], " "), function(z) paste(z[1], collapse = " "))

# check how gbif would classify species
# this is too general, how the data is delivered will be better
gbif <- name_backbone_checklist(names$`scientific name`[is.na(names$name)])


# get all group level observations
names$type[grepl("-gr.", names$`scientific name`)] <- "Group"
names$name[grepl("-gr.", names$`scientific name`)] <- names$`scientific name`[grepl("-gr.", names$`scientific name`)]


# check gbif again, this time removing the 'indet.' mark
indet <- names[grepl("indet.", names$`scientific name`),]
gbif <- name_backbone_checklist(gsub(" indet.", "", indet$`scientific name`))

# get data to change the families
check <- gbif[, c(19,11)]
check$family[!is.na(check$family)] <- "Family"
check$family[grepl("ni$", check$verbatim_name)] <- "Tribe"
check$family[grepl("nae$", check$verbatim_name)] <- "Subfamily"
# assign to indet
indet$name <- check$verbatim_name
indet$type <- check$family
# assign to names
names$type[is.na(names$type)] <- indet$type[match(names$`scientific name`[is.na(names$type)], indet$`scientific name`)]
names$name[is.na(names$name)] <- indet$name[match(names$`scientific name`[is.na(names$name)], indet$`scientific name`)]


# check the ones that are not yet know
not_yet <- names[is.na(names$name),]
# these really are a lot still
# mostly due to the 'aardhommelcomplex'
sum(not_yet$n)
# we will keep the names and call them 'complexes'
names$type[is.na(names$name)] <- "Complex"
names$name[is.na(names$name)] <- names$`scientific name`[is.na(names$name)]
```


## 2.2 Phylogeny
```{r}
# create subspecies column and assign
names$subspecies <- NA
names$subspecies[names$type=="Subspecies"] <- names$name[names$type=="Subspecies"]

# species names
names$species <- NA
names$species[names$type=="Species"] <- names$name[names$type=="Species"]
names$species[names$type=="Synonym"] <- names$name[names$type=="Synonym"]
names$species[names$type=="Subspecies"] <- sapply(strsplit(names$subspecies[!is.na(names$subspecies)], " "), function(z) paste(z[1:2], collapse = " "))
names$species[names$type=="Forma"] <- names$name[names$type=="Forma"]
names$species[names$type=="Variety"] <- sapply(strsplit(names$name[names$type=="Variety"], " "), function(z) paste(z[1:2], collapse = " "))

# genus names
names$genus <- NA
names$genus[names$type=="Genus"] <- names$name[names$type=="Genus"]
names$genus[is.na(names$genus) & !is.na(names$species)] <-  
  sapply(strsplit(names$species[is.na(names$genus) & !is.na(names$species)], " "), function(z) paste(z[1], collapse = " "))
# also add for group and complexes
names$genus[names$type=="Complex"] <- sapply(strsplit(names$name[names$type=="Complex"], " "), function(z) paste(z[1], collapse = " "))
names$genus[names$type=="Group"] <- sapply(strsplit(names$name[names$type=="Group"], " "), function(z) paste(z[1], collapse = " "))
```


```{r}
# get family names
names$family <- NA
names$family[names$type=="Family"] <- names$name[names$type=="Family"]

# get additional family data
gbif <- name_backbone_checklist(names$name)

#assign names
names$family <- gbif$family

# assign names for genera
names$family[is.na(names$family) & !is.na(names$genus)] <- names$family[match(names$genus[is.na(names$family) & !is.na(names$genus)] ,
                                                                              names$genus[!is.na(names$family)])]


families <- c(Anthidiini   = "Megachilidae", Anthophorinae = "Apidae", Anthophorini = "Apidae", Eucerinae    = "Apidae", Eucerini = "Apidae",
              Halictinae   = "Halictidae",Halictini  = "Halictidae",  Megachilini  = "Megachilidae", Meliponini   = "Apidae",
              Nomadinae    = "Apidae",Nomioidini = "Halictidae",Osmiini = "Megachilidae",Panurginae   = "Andrenidae",Panurgini = "Andrenidae")

# assign the rest myself
names$family[is.na(names$family)] <- families

# some species are not yet assigned because they are complexes
names$species[names$type =="Complex"] <- names$name[names$type =="Complex"]
```


## 2.3 Check names
```{r}
# check all synonyms and assign gbif name
synonyms <- gbif[gbif$status=="SYNONYM" & !is.na(gbif$status),]

# get species names of these
synonyms_names <- names[names$name %in% synonyms$verbatim_name,]

# add columns to data
synonyms$GBIF <- NA
synonyms_names$accepted_GBIF <- NA
synonyms_names$rank <- NA

# run for all synonyms
for(i in 1: nrow(synonyms)){
  # get synonym data
  acc <- name_usage( key = synonyms$acceptedUsageKey[i])
  # add name of accepted species
  synonyms$GBIF[i] <- acc$data$canonicalName
  # also add to the names part
  synonyms_names$accepted_GBIF[i] <- acc$data$canonicalName
  synonyms_names$rank <- acc$data$rank
}

# assign column to data with gbif name
names$GBIF <- NA
names$GBIF <- synonyms_names$accepted_GBIF[match(names$name, synonyms_names$name)]
names$GBIF[is.na(names$GBIF)] <- gbif$canonicalName[match(names$name[is.na(names$GBIF)], gbif$verbatim_name)]
```


## 2.4 Save
Save names for further use, especially important if we will also use species names later from other databases
```{r}
write_csv(names, "../Data/Names/Names_pollinators_observation.csv")
```

Assign to observations
```{r}
# read data
names <- read_csv("../Data/Names/Names_pollinators_observation.csv")

# assign
obs$name <- names$name[match(obs$`scientific name`, names$`scientific name`)]
obs$pol_subspecies <- names$subspecies[match(obs$`scientific name`, names$`scientific name`)]
obs$pol_species <- names$species[match(obs$`scientific name`, names$`scientific name`)]
obs$pol_genus <- names$genus[match(obs$`scientific name`, names$`scientific name`)]
obs$pol_family <- names$family[match(obs$`scientific name`, names$`scientific name`)]
obs$pol_rank <- names$type[match(obs$`scientific name`, names$`scientific name`)]


# check number of new species
length(unique(names$name))

# now we will check for the number of species from different types
names |> group_by(type) |> summarise(n=n())
```

# PLANT
## 1 NAMES 
```{r}
# get plant names
names <- obs |> group_by(`related species`, `related species name`) |> summarise(n=n())

# remove additional texts like cultivar
names$taxa <- NA
names$taxa <- gsub("\\s*\\([^)]*\\)", "", names$`related species`)
names$taxa <- gsub("\\s+s\\.l\\.", "", names$taxa)
names$taxa <- gsub("\\s*spec\\.?\\s*$", "", names$taxa)
names$taxa <- gsub("\\s*indet\\.?\\s*$", "", names$taxa)
names$taxa <- gsub("\\s*agg\\.?\\s*$", "", names$taxa)
names$taxa <- gsub("\\s*spec\\.", "", names$taxa)


# remove varieties
names$taxa <- gsub("\\s*\\'[^']*\\'", "", names$taxa)
# remove 'forma' identifications
names$taxa <- gsub("\\s*f\\..*$", "", names$taxa)
# remove sections
names$taxa <- gsub("\\s*subsect\\..*$", "", names$taxa)
names$taxa <- gsub("\\s*sect\\..*$", "", names$taxa)
```


## 2 GBIF
## 2.1 Backbone
```{r}
# further cleaning to ensure that GBIF can recognise is
# make UTF proof
names$taxa <- gsub("[\u0080-\uFFFF]", "", names$taxa)     
# remove spaces
names$taxa <- gsub("\\s+", " ", names$taxa)        
# remove spaces at end
names$taxa <- trimws(names$taxa)              
# remove NA data
names$taxa[names$taxa == ""] <- NA  
names <- names[!is.na(names$taxa),]
# how many names are original 
length(unique(names$taxa))

# create dataframe
gbif <- name_backbone_checklist(names$taxa[1])
# subdivide to avoid R crashing
for(i in 1: 10){
  # boundaries
  begin <- 1 + floor(length(names$taxa)/10*(i-1))
  end <- floor(length(names$taxa)/10 * i)
  # run 
  data <- name_backbone_checklist(names$taxa[begin: end])
  gbif <- bind_rows(gbif, data)
}

# remove duplicates
gbif <- gbif[!duplicated(gbif$verbatim_name),]
```


## 2.2 Assign
```{r}
# remove all plant names
names <- names[names$taxa %in% gbif$verbatim_name[gbif$kingdom == "Plantae" | is.na(gbif$kingdom)],]
gbif <- gbif[gbif$kingdom == "Plantae" | is.na(gbif$kingdom),]

# assign accepted names to name database 
gbif$status[gbif$status=="DOUBTFUL" & !is.na(gbif$status)] <- "ACCEPTED"
gbif_accepted <- gbif[gbif$status=="ACCEPTED" & !is.na(gbif$status),]
gbif_higher_rank <- gbif_accepted[gbif_accepted$matchType == "HIGHERRANK",]
gbif_accepted <- gbif_accepted[gbif_accepted$matchType == "EXACT",]
# assign names
names$GBIF <- gbif_accepted$canonicalName[match(names$taxa, gbif_accepted$verbatim_name)]

# also assign accepted genus and family, and add overall kingdom to name database 
# assign names
names$genus <- gbif_accepted$genus[match(names$taxa, gbif_accepted$verbatim_name)]
names$family <- gbif_accepted$family[match(names$taxa, gbif_accepted$verbatim_name)]
names$kingdom <- gbif_accepted$kingdom[match(names$taxa, gbif_accepted$verbatim_name)]

# add level
names$type <- tolower(gbif_accepted$rank[match(names$taxa, gbif_accepted$verbatim_name)])
```


```{r}
# check higher rank complexes
double_species <- gbif_higher_rank |>filter(str_detect(verbatim_name, "\\+"))
double_species <- double_species |>  mutate(species_list = str_extract_all(verbatim_name,  "[A-Z][a-z]+(?:\\s+(?:[x×]\\s+)?[a-z]+)?"))
double_species <- double_species |> mutate(species_wide = map(species_list,  ~ setNames(  .x, paste0("species_", seq_along(.x)) ))) |>
  unnest_wider(species_wide)

# check names official
double_species_check1 <-  name_backbone_checklist(double_species$species_1)
double_species_check1$original <- double_species$verbatim_name
double_species_check2 <-  name_backbone_checklist(double_species$species_2)
double_species_check2$original <- double_species$verbatim_name
double_species_check3 <-  name_backbone_checklist(double_species$species_3)
double_species_check3$original <- double_species$verbatim_name

# merge
double_species$checked <- paste(double_species_check1$canonicalName, double_species_check2$canonicalName, double_species_check3$canonicalName, sep = " + " )
double_species$checked <- gsub(" ?\\+ ?NA", "", double_species$checked)

# genus
double_species$genus_checked <- double_species_check1$genus
double_species$genus_checked[double_species$verbatim_index %in% c(153)] <- c("Tripleurospermum + Matricaria")
double_species$genus_checked[double_species$verbatim_index %in% c(135)] <- c("Brassica + Sinapis")
double_species$checked[double_species$verbatim_index %in% c(135)] <- NA

# family
double_species$family_checked <- double_species_check1$family

# kingdom
double_species$kingdom <- double_species_check1$kingdom

# names
names$GBIF[names$taxa %in% double_species$verbatim_name] <- double_species$checked[match(names$taxa[names$taxa %in% double_species$verbatim_name],
                                                                                         double_species$verbatim_name)]
# genus
names$genus[names$taxa %in% double_species$verbatim_name] <- double_species$genus_checked[match(names$taxa[names$taxa %in% double_species$verbatim_name],
                                                                                         double_species$verbatim_name)]
# family
names$family[names$taxa %in% double_species$verbatim_name] <- double_species$family_checked[match(names$taxa[names$taxa %in% double_species$verbatim_name],
                                                                                         double_species$verbatim_name)]
# kingdom
names$kingdom[names$taxa %in% double_species$verbatim_name] <- double_species$kingdom[match(names$taxa[names$taxa %in% double_species$verbatim_name],
                                                                                         double_species$verbatim_name)]
# type
names$type[names$taxa %in% double_species$verbatim_name] <- "complex"
names$type[names$taxa %in% c("Brassica + Sinapis")] <- "complex genus"

```


```{r}
# check remaining higher ranks
gbif_higher_rank <- gbif_higher_rank[!gbif_higher_rank$verbatim_name %in% double_species$verbatim_name,]
higher_rank_genera <- gbif_higher_rank[is.na(vegdata::parse.taxa(gbif_higher_rank$verbatim_name)$epi1),]

# assign these
names$genus[is.na(names$genus)] <- higher_rank_genera$genus[match(names$taxa[is.na(names$genus)], higher_rank_genera$verbatim_name)]
names$family[is.na(names$family)]<- higher_rank_genera$family[match(names$taxa[is.na(names$family)], higher_rank_genera$verbatim_name)]
names$type[is.na(names$type)]<- tolower(higher_rank_genera$rank[match(names$taxa[is.na(names$type)], higher_rank_genera$verbatim_name)])
names$kingdom[is.na(names$kingdom)]<- higher_rank_genera$kingdom[match(names$taxa[is.na(names$kingdom)], higher_rank_genera$verbatim_name)]

# check species
higher_rank_species <- gbif_higher_rank[!gbif_higher_rank$verbatim_name %in% higher_rank_genera$verbatim_name,]

# check against powo
# check in powo 
names_powo <- match_knms(higher_rank_species$verbatim_name)
names_powo <- names_powo$results

# safe depending on types
safe_names <- c()
multiple <- c()
none <- c()

# results can be false true multiple_matches
for(i in 1: length(names_powo)){
  if(names_powo[[i]][[2]]== "true"){
    safe_names <- rbind(safe_names, names_powo[[i]][[1]])
  } else if(names_powo[[i]][[2]]=="multiple_matches"){
    multiple <- rbind(multiple, names_powo[[i]][[1]])
  } else if(names_powo[[i]][[2]]=="false"){
    none <- rbind(none, names_powo[[i]][[1]])
  }
}

# assign the save names
names$GBIF[names$taxa %in% safe_names] <- safe_names[match(names$taxa[names$taxa %in% safe_names], safe_names)] 
names$genus[names$taxa %in% safe_names] <- vegdata::parse.taxa(names$taxa[names$taxa %in% safe_names])$genus
names$genus[names$taxa %in% safe_names] <- vegdata::parse.taxa(names$taxa[names$taxa %in% safe_names])$genus
names$family[names$taxa %in% higher_rank_species$verbatim_name] <- 
  higher_rank_species$family[match(names$taxa[names$taxa %in% higher_rank_species$verbatim_name], higher_rank_species$verbatim_name)]
names$kingdom[names$taxa %in% higher_rank_species$verbatim_name] <- "Plantae"

# check none
none_change <- data.frame(old = c("Anchusa undulata subsp. hybrida", "Clinopodium calamintha subsp. spruneri", "Salix hybrid", 
                                  "Trifolium medium subsp. medium"),
                          new = c("Anchusa hybrida","Clinopodium nepeta subsp. spruneri", "Salix", "Trifolium medium"))
# adapt data frame
none_change <- rbind(none_change, data.frame( old = none[! none %in% none_change$old], new =  none[! none %in% none_change$old]))
none_change$type <- ifelse(grepl("subsp.", none_change$new), "subspecies","species")
none_change$type[c(3,6,11)] <- c("genus","variety","hybrid")

# also look at multiple
multiple_change <- data.frame(old= c(multiple),
                              new = c("Allium porrum","Symphyotrichum lanceolatum", "Psephellus dealbatus",  "Lophiolepis ferox", "Cytisus hirsutus",
                                      "Erica carnea", "Ageratina altissima", "Trommsdorffia uniflora", "Limbarda crithmoides","Pentanema spiraeifolium",
                                      "Pentanema hirtum", "Leontodon crispus","Lotus tenuis","Lotus uliginosus","Solanum lycopersicum",
                                      "Trifolium speciosum"))

# multiple change
multiple_change$type <- "species"

# bind
none_change <- rbind(none_change, multiple_change)

# assign the save names
names$GBIF[names$taxa %in% none_change$old] <- none_change$new[match(names$taxa[names$taxa %in% none_change$old], none_change$old)] 
names$genus[names$taxa %in% none_change$old] <- vegdata::parse.taxa(names$GBIF[names$taxa %in% none_change$old])$genus
names$type[names$taxa %in% none_change$old] <- none_change$type[match(names$taxa[names$taxa %in% none_change$old], none_change$old)] 
```



## 2.3 Synonyms
```{r}
# look at synonyms
gbif_synonyms <- gbif[gbif$status=="SYNONYM" & !is.na(gbif$status),]
# remove the non-plant observations
names <- names[!names$taxa %in% gbif_synonyms$verbatim_name[gbif_synonyms$kingdom != "Plantae" | is.na(gbif_synonyms$kingdom)],]
gbif_synonyms <- gbif_synonyms[! (gbif_synonyms$kingdom != "Plantae" | is.na(gbif_synonyms$kingdom)),]

# add columns to data
synonyms <- data.frame(GBIF = character(nrow(gbif_synonyms)), genus = character(nrow(gbif_synonyms)), family = character(nrow(gbif_synonyms)), 
                       kingdom =  character(nrow(gbif_synonyms)), level = character(nrow(gbif_synonyms)), 
                       status= character(nrow(gbif_synonyms)),stringsAsFactors = FALSE)

# run for all synonyms
for(i in 1: nrow(gbif_synonyms)){
  # get synonym data
  acc <- name_usage( key = gbif_synonyms$acceptedUsageKey[i])
  # add name of accepted species
  synonyms$GBIF[i] <- acc$data$canonicalName
  synonyms$genus[i] <- acc$data$genus
  synonyms$family[i] <- acc$data$family
  synonyms$level[i] <- acc$data$rank
  synonyms$kingdom[i] <- acc$data$kingdom
  synonyms$status[i] <- acc$data$taxonomicStatus
}

# link with original name 
synonyms$taxa <- gbif_synonyms$verbatim_name

# also assign accepted genus and family, and add overall kingdom to name database 
# assign names 
names$GBIF[is.na(names$GBIF)] <- synonyms$GBIF[match(names$taxa[is.na(names$GBIF)] , synonyms$taxa)] 
names$genus[is.na(names$genus)] <- synonyms$genus[match(names$taxa[is.na(names$genus)] , synonyms$taxa)] 
names$family[is.na(names$family)] <- synonyms$family[match(names$taxa[is.na(names$family)] , synonyms$taxa)] 
names$type[is.na(names$type)] <- tolower(synonyms$level[match(names$taxa[is.na(names$type)] , synonyms$taxa)]) 
names$kingdom[is.na(names$kingdom)] <- synonyms$kingdom[match(names$taxa[is.na(names$kingdom)] , synonyms$taxa)] 
```


## 2.4 Remaining
```{r}
# are there any observations remaining
gbif_remaining <- gbif[!gbif$verbatim_name %in% names$taxa[!is.na(names$kingdom)],]

# assign the fuzzy
gbif_fuzzy <- gbif_remaining[!is.na(gbif_remaining$canonicalName),]

# assign names 
names$GBIF[is.na(names$GBIF)] <- gbif_fuzzy$canonicalName[match(names$taxa[is.na(names$GBIF)] , gbif_fuzzy$verbatim_name)] 
names$genus[is.na(names$genus)] <- gbif_fuzzy$genus[match(names$taxa[is.na(names$genus)] , gbif_fuzzy$verbatim_name)] 
names$family[is.na(names$family)] <- gbif_fuzzy$family[match(names$taxa[is.na(names$family)] , gbif_fuzzy$verbatim_name)] 
names$type[is.na(names$type)] <- tolower(gbif_fuzzy$rank[match(names$taxa[is.na(names$type)] , gbif_fuzzy$verbatim_name)]) 
names$kingdom[is.na(names$kingdom)] <- gbif_fuzzy$kingdom[match(names$taxa[is.na(names$kingdom)] , gbif_fuzzy$verbatim_name)] 

# look at observations not yet present
remaining <- names[is.na(names$kingdom),]
```

Check against POWO
```{r}
# check in powo 
names_powo <- match_knms(remaining$taxa)
names_powo <- names_powo$results

# safe depending on types
safe_names <- c()
multiple <- c()
none <- c()

# results can be false true multiple_matches
for(i in 1: length(names_powo)){
  if(names_powo[[i]][[2]]== "true"){
    safe_names <- rbind(safe_names, names_powo[[i]][[1]])
  } else if(names_powo[[i]][[2]]=="multiple_matches"){
    multiple <- rbind(multiple, names_powo[[i]][[1]])
  } else if(names_powo[[i]][[2]]=="false"){
    none <- rbind(none, names_powo[[i]][[1]])
  }
}
```


Safe
```{r}
# check multiple
multiple
# all look good
# assign to safe names
safe_names <- c(safe_names, multiple)
safe_names <- safe_names[!safe_names %in% "Osmia"]

# assign the save names
remaining$genus[remaining$taxa %in% safe_names] <- remaining$taxa[remaining$taxa %in% safe_names] 
remaining$type[remaining$taxa %in% safe_names] <- "genus"
remaining$kingdom[remaining$taxa %in% safe_names] <- "Plantae"
# some extra
remaining[remaining$taxa %in% "Iris orientalis",c(5:7, 9)] <- data.frame("Iris orientalis","Iris",
                                                                         "Iridaceae","species")
remaining[remaining$taxa %in% "Salix alba",c(5:7, 9)] <- data.frame("Salix alba","Salix",
                                                                         "Salicaceae","species")

# also add to the data
names[is.na(names$kingdom),] <- remaining

# check family 
family_known <- unique(names[!is.na(names$genus)& !is.na(names$family), c(6,7)])
names$family[is.na(names$family)] <- family_known$family[match(names$genus[is.na(names$family)],
                                                               family_known$genus)]

# get remaining again
remaining <- names[is.na(names$kingdom),]
```

Check remaining
```{r}
# write clipboard
writeClipboard(remaining$taxa)

# output chatGPT
plants <- data.frame(
  original_name = c("Anthemideae","Astereae","Bambusoideae",  "Calendulaea", "Cardueae",
                    "Carduoideae","Cichorieae", "Crocus chrysanthus + Crocus x luteus",
                    "Fallopia japonica + Fallopia sachalinensis + Fallopia x bohemica", 
                    "Hyacinthoides hispanica + Hyacinthoides x massartiana",
                    "Hypericum androsaemum + Hypericum hircinum + Hypericum x inodorum",   
                    "Hypericum maculatum + Hypericum perforatum + Hypericum x desetangsii",
                    "Mentha aquatica + Mentha x verticillata","Mentha suaveolens + Mentha x rotundifolia",
                    "Populus alba + Populus x canescens",
                    "Salix babylonica + Salix x pendulina + Salix x sepulcralis","Salix udensis x Salix caprea",
                    "Salix udensis x Salix viminalis","Senecieae",
                    "Tilia cordata + Tilia platyphyllos + Tilia x europaea",
                    "Vaccinium angustifolium x Vaccinium corymbosum",
                    "Veronica longifolia + Veronica spicata x Veronica longifolia",
                    "Viola reichenbachiana + Viola riviniana + Viola x bavarica","Viola tricolor group"),
  final_name = c( "Anthemideae","Astereae", "Bambusoideae","Calendulaea", "Cardueae",
                  "Carduoideae","Cichorieae", "Crocus chrysanthus + Crocus x luteus",
                  "Fallopia japonica + Fallopia sachalinensis + Fallopia x bohemica", 
                  "Hyacinthoides hispanica + Hyacinthoides x massartiana",
                  "Hypericum androsaemum + Hypericum hircinum + Hypericum x inodorum",
                  "Hypericum maculatum + Hypericum perforatum + Hypericum x desetangsii",
                  "Mentha aquatica + Mentha x verticillata",  "Mentha suaveolens + Mentha x rotundifolia",
                  "Populus alba + Populus x canescens",
                  "Salix babylonica + Salix x pendulina + Salix x sepulcralis",  
                  "Salix udensis x Salix caprea","Salix udensis x Salix viminalis",
                  "Senecieae","Tilia cordata + Tilia platyphyllos + Tilia x europaea",
                  "Vaccinium angustifolium x Vaccinium corymbosum",
                  "Veronica longifolia + Veronica spicata x Veronica longifolia",  
                  "Viola reichenbachiana + Viola riviniana + Viola x bavarica",
                  "Viola tricolor"),
  genus = c(NA, NA, NA, NA, NA, NA, NA, "Crocus", "Fallopia", "Hyacinthoides", "Hypericum",
            "Hypericum","Mentha", "Mentha", "Populus", "Salix", "Salix", "Salix",
            NA, "Tilia", "Vaccinium", "Veronica", "Viola", "Viola"),
  family = c( "Asteraceae","Asteraceae","Poaceae","Asteraceae","Asteraceae","Asteraceae","Asteraceae",
              "Iridaceae","Polygonaceae","Asparagaceae","Hypericaceae",
              "Hypericaceae",
              "Lamiaceae","Lamiaceae","Salicaceae","Salicaceae","Salicaceae","Salicaceae","Asteraceae",
              "Malvaceae","Ericaceae","Plantaginaceae",
              "Violaceae","Violaceae"),
  rank = c( "tribe","tribe","subfamily","subfamily","tribe","subfamily","tribe","complex","complex",
            "complex","complex","complex","complex","complex","complex","complex","hybrid",
            "hybrid","tribe","complex","hybrid","complex","complex","species"),stringsAsFactors = FALSE)

# add genus, family, species and type
remaining$genus <- plants$genus[match(remaining$taxa, plants$original_name)]
remaining$family <- plants$family[match(remaining$taxa, plants$original_name)]
remaining$type <- plants$rank[match(remaining$taxa, plants$original_name)]
remaining$GBIF <- plants$final_name[match(remaining$taxa, plants$original_name)]
remaining$kingdom[!is.na(remaining$family)] <- "Plantae"

# add to names
names[is.na(names$kingdom),] <- remaining

# check which we will remove
remaining <- names[is.na(names$kingdom),]

# remove remaining observations
names <- names[!is.na(names$kingdom),]
names <- names[!is.na(names$taxa),]

# remove phylum level observations
names <- names[!names$type =="phylum",]
names <- names[!names$type =="class",]
names <- names[!names$type =="kingdom",]
names <- names[!is.na(names$`related species`),]
names$type[names$type =="form"] <- "species"
names[names$taxa =="Cymbalaria",c(5:7,9)] <- data.frame("Cymbalaria","Cymbalaria","Plantaginaceae","genus")

# change type for complexes
names$type[grepl("\\ x ", names$taxa)] <- "hybrid"
names$type[grepl("\\+", names$taxa)] <- "complex"
```

## 2.5 Phylogeny
```{r}
# there is something with some varieties, change subspecies again to correct type
names$type[names$type== "variety" & grepl("subsp.", names$taxa)] <- "subspecies"

# create subspecies column and assign
names$subspecies <- NA
names$subspecies[names$type=="subspecies"] <- names$taxa[names$type=="subspecies"]

# species names
unique(names$type) 
names$species <- NA
names$species[names$type=="species"] <- names$GBIF[names$type=="species"]
names$species[names$type=="subspecies"] <- sapply(strsplit(names$subspecies[!is.na(names$subspecies)], " "), 
                                                  function(z) paste(z[1:2], collapse = " "))
names$species[names$type=="variety"] <- sapply(strsplit(names$taxa[names$type=="variety"], " "), 
                                               function(z) paste(z[1:2], collapse = " "))
names$species[names$type=="complex"] <- names$GBIF[names$type=="complex"]
names$species[names$type=="hybrid"] <- names$GBIF[names$type=="hybrid"]
# check which types remain
unique(names$type[is.na(names$species)])

# genus names
names$genus_gbif <- names$genus
names$genus <- NA
names$genus[names$type=="genus"] <- names$genus_gbif[names$type=="genus"]
names$genus[is.na(names$genus) & !is.na(names$species)] <-  
  sapply(strsplit(names$species[is.na(names$genus) & !is.na(names$species)], " "), 
         function(z) paste(z[1], collapse = " "))

# check which types remain
unique(names$type[is.na(names$genus)])
```

```{r}
# get family names
missing_family <- names[is.na(names$family),]

# check family 
family_known <- unique(names[!is.na(names$genus)& !is.na(names$family), c(6,7)])
# check again in family database
missing_family$family <- family_known$family[match(missing_family$genus, family_known$genus)]

# none is known, assign ourselves
writeClipboard(missing_family$genus_gbif)
# data
genus_family <- c("Rosaceae","Amaranthaceae","Plantaginaceae","Scrophulariaceae","Cactaceae", "Polemoniaceae","Plantaginaceae",
                  "Asteraceae","Desmidiaceae", "Haloragaceae","Scrophulariaceae","Lamiaceae","Rosaceae","Solanaceae",
                  "Fabaceae", "Polypodiaceae","Amaranthaceae")
missing_family$family <- genus_family

# assign to names
names[is.na(names$family),] <- missing_family
```


```{r}
# genus check some left
genus_not_yet <- names[is.na(names$genus) ,]
# change some
genus_not_yet$genus[genus_not_yet$taxa %in% "Taraxacum"] <- "Taraxacum"
genus_not_yet$type[genus_not_yet$taxa %in% "Taraxacum"] <- "genus"
# Cardaminopsis
genus_not_yet$genus[genus_not_yet$taxa %in% "Cardaminopsis"] <- "Arabis"
genus_not_yet$type[genus_not_yet$taxa %in% "Cardaminopsis"] <- "genus"
# Cnicus
genus_not_yet$genus[genus_not_yet$taxa %in% "Cnicus"] <- "Centaurea"
genus_not_yet$type[genus_not_yet$taxa %in% "Cnicus"] <- "genus"

names[is.na(names$genus) ,] <- genus_not_yet
```


## 3 SAVE
```{r}
# look at numbers
names |> group_by(type) |> summarise(n=n())

# write csv
write_csv(names, "../Data/Names/Names_plants_observation.csv")

# assign to obs
obs$plant <- names$taxa[match(obs$`related species`, names$`related species`)]
obs$obs_subspecies <- names$subspecies[match(obs$`related species`, names$`related species`)]
obs$obs_species <- names$species[match(obs$`related species`, names$`related species`)]
obs$obs_genus <- names$genus[match(obs$`related species`, names$`related species`)]
obs$obs_family <- names$family[match(obs$`related species`, names$`related species`)]
obs$obs_rank <- names$type[match(obs$`related species`, names$`related species`)]

obs <- obs |> relocate(plant, .before= obs_species)
obs <- obs |> relocate(obs_subspecies, .before= obs_species)

write_csv(obs, "../Data/Observation/observation_org_bees.csv")
```


# LAST CHECK
```{r}
# read data
obs <- read_csv( "../Data/Observation/observation_org_bees.csv", show_col_types = FALSE)

# check status
unique(obs$`validation status`)
numbers <- obs |> group_by(`validation status`) |> summarise(n=n())
sum(numbers$n[1:3])

# remove rejected
obs <- obs[!obs$`validation status` == "rejected", ]

# save
write_csv(obs, "../Data/Observation/observation_org_bees.csv")
```

