---
title: "2_Plantnet"
author: "Willem"
date: "2025-10-01"
output: html_document
---


# INTRO
Empty environment
```{r}
rm(list=ls())
```

Load packages
```{r}
library(tidyverse)
library(plantnet)
library(httr)
library(utils)
library(jsonlite)
```


Load data
```{r}
polplant_original <- read_csv("../Data/polplant.csv",show_col_types = FALSE)
poldata_original <- read_csv("../Data/poldata.csv", show_col_types = FALSE)
pictures_polplant <- read_csv("../Data/polplant_pictures.csv",show_col_types = FALSE)
pictures_poldata <- read_csv("../Data/poldata_pictures.csv", show_col_types = FALSE)
```


# POLPLANT
# 1 Link
Link with folder
```{r}
image_folder <- "D:/Data Natuurpunt/batch1"
# Create full paths using the image names
image_files <- file.path(image_folder, paste0(pictures_polplant$foto_id, ".jpg")) 
# Filter to include only existing files (avoid errors)
image_files <- image_files[file.exists(image_files)]
```


# 2 Plantnet
Link with folder
```{r}
image_folder <- "D:/Data Natuurpunt/batch1"
# Create full paths using the image names
image_files <- file.path(image_folder, paste0(pictures_polplant$foto_id, ".jpg")) 
# Filter to include only existing files (avoid errors)
image_files <- image_files[file.exists(image_files)]
```


```{r}
result_list <-read_rds("../Results/polplant_identification.RData")
already_identified <- names(result_list)
```


```{r}
# key
api_key <- "2b10bu236VtELMT8bV13UQb73e"

# Set the API endpoint
url <- paste0("https://my-api.plantnet.org/v2/identify/all?api-key=", api_key)

# get pictures per id
id_polplant <- unique(polplant_original$ID[!is.na(polplant_original$PictureID)])
# remove already done
id_polplant <- id_polplant[!id_polplant %in% as.numeric(already_identified)]
# reduce size (for identification)
id_polplant <- id_polplant[1:200]


results_list <- list()

for(id in id_polplant){
  
  # get all IDs corresponding to that plant species
  pictures_id <- pictures_polplant$foto_id[pictures_polplant$wnm_id %in% id]
  
  # get place in dataset
  picturesURL_all <- file.path(image_folder, paste0(pictures_id, ".jpg")) 
  
  # Split into chunks of 5 images each (PlantNet limit)
  chunks <- ceiling(length(picturesURL_all)/5)
  
  results_polplant <- data.frame(ID = numeric(),Score = numeric(), Name = character(), Common_name = character(), Name_author= character(),
                                 Genus= character(), Genus_author= character(), Family = character(), Family_author = character(), 
                                 GBIF_ID = character(),POWO_ID = character(), IUCN_ID = character(), IUCN = character())
  
  results_polplant_organs <- data.frame(ID= numeric(),Picture_ID = character(), Organ = character(), Score = numeric() )
  chunk=1
  for (chunk in 1: chunks) {
    length_chunks <- ceiling(length(picturesURL_all)/chunks) 
    # create begin and end values for the plot observation ID
    min_chunk<- ((chunk-1)*length_chunks+1)
    max_chunk<- (chunk*length_chunks)

    if(max_chunk>length(picturesURL_all)){
      max_chunk <- length(picturesURL_all)
    }
      
    picturesURL <- picturesURL_all[min_chunk: max_chunk]
    
    # create body to put images together in the API url
    body <- c(setNames(lapply(picturesURL, upload_file), rep("images", length(picturesURL))),
              setNames(as.list(rep("auto", length(picturesURL))), rep("organs", length(picturesURL))))
    
    # use POST to upload images
    response <- POST(url, body = body, encode = "multipart")
  
    if (response$status_code == 200) {
      # get result from response and make it a table
      result <- content(response, as = "text", encoding = "UTF-8")
  
      # make data frame
      parsed_result <- fromJSON(result, flatten = TRUE)
      # get organ predicted
      predicted_organ <- parsed_result$predictedOrgans[,2:4]
      predicted_organ <- cbind(rep(id, nrow(parsed_result$predictedOrgans)), predicted_organ)
      predicted_organ$filename <- gsub(".jpg","", predicted_organ$filename)
      colnames(predicted_organ) <- c("ID","Picture_ID","Organ","Score")
  
      # get plants predicted and change names
      predicted_plant <- cbind(rep(id, nrow(parsed_result$results)), parsed_result$results)
      if(ncol(predicted_plant)>14){
          predicted_plant <- predicted_plant[, c(1,2,3,5,6,7,9,10,12,13,14,15,16)]
          colnames(predicted_plant) <- c("ID","Score","Name","Common_name","Name_author","Genus","Genus_author","Family","Family_author","GBIF_ID",
                                         "POWO_ID","IUCN_ID","IUCN")
      } else {
          predicted_plant <- predicted_plant[, c(1,2,3,5,6,7,9,10,12,13,14)]
          colnames(predicted_plant) <- c("ID","Score","Name","Common_name","Name_author","Genus","Genus_author","Family","Family_author",
                                         "GBIF_ID","POWO_ID")
      }
      
      # only save the first common name given
      for(com_id in 1: nrow(parsed_result$results)){
        predicted_plant$Common_name[[com_id]] <- as.character(predicted_plant$Common_name[[com_id]][1])
      }
      predicted_plant$Common_name <- as.character(predicted_plant$Common_name)
            
      # Store results in a list (create a data frame for this image)
      
      results_polplant <- bind_rows(results_polplant, predicted_plant)
      results_polplant_organs <- bind_rows(results_polplant_organs, predicted_organ)
      } else {
      add <- data.frame(ID= as.numeric(as.character((id))), Score = as.numeric(NA), Name = NA, Common_name = NA, Name_author= NA,
                                Genus= NA, Genus_author= NA, Family = NA, Family_author = NA, 
                                GBIF_ID = NA, POWO_ID = NA, IUCN_ID = NA, IUCN = NA)
    
      results_polplant <- bind_rows(results_polplant, add)
      add_organs <- data.frame(ID= as.numeric(as.character((id))), Picture_ID = as.character(NA), Organ = NA, Score = NA)
      results_polplant_organs <- bind_rows(results_polplant_organs, add_organs)
      }
    results_list[[as.character(id)]] <- list(predicted_organ = results_polplant_organs, predicted_plant = results_polplant)
  }
  
}

results_list <- c(result_list, results_list)

write_rds(results_list, "../Results/polplant_identification.RData")
```



Retrieve all with highest scores
```{r}
results_list <-read_rds("../Results/polplant_identification.RData")

# create empty data frame to paste most likely results in
polplant_plantnet <- data.frame(ID = numeric(),Score = numeric(), Name = character(), Common_name = character(), Name_author= character(),
                                Genus= character(), Genus_author= character(), Family = character(), Family_author = character(), 
                                GBIF_ID = character(),POWO_ID = character(), IUCN_ID = character(), IUCN = character(), Identification = character())

id_polplant <- as.numeric(names(results_list))

# create final dataset from the list 
for(id in id_polplant){
  # predicted data for that observation ID
  predicted <-   results_list[[as.character(id)]]
  if(all(is.na(predicted$predicted_organ$Organ))){
    add <- data.frame(ID= as.numeric(as.character((id))), Score = as.numeric(NA), Name = NA, Common_name = NA, Name_author= NA,
                                Genus= NA, Genus_author= NA, Family = NA, Family_author = NA, 
                                GBIF_ID = NA, POWO_ID = NA, IUCN_ID = NA, IUCN = NA, Identification = "None")
    
    polplant_plantnet <- bind_rows(polplant_plantnet, add)
  } else if(any(predicted$predicted_organ$Organ[!is.na(predicted$predicted_organ$Organ)] == "flower")){
    polplant_plantnet <- bind_rows(polplant_plantnet, c(predicted$predicted_plant[which.max(predicted$predicted_plant$Score),], Identification ="Flower"))
  } else {
    organ_identified <- names(sort(table(predicted$predicted_organ$Organ), decreasing=TRUE)[1])
    polplant_plantnet <- bind_rows(polplant_plantnet, c(predicted$predicted_plant[which.max(predicted$predicted_plant$Score),], Identification ="Flower"))
  }
}

check_picture_id <- pictures_polplant$foto_id[pictures_polplant$wnm_id %in% polplant_plantnet$ID[is.na(polplant_plantnet$Name)]]

identified_picture_id  <- pictures_polplant$foto_id[pictures_polplant$wnm_id %in% polplant_plantnet$ID[!is.na(polplant_plantnet$Name)]]
```


# 3 Link
## 3.1 Check species names
```{r}
# link data
link_data <- polplant_plantnet[,c(1,2,3,6,8,10,11)]
colnames(link_data) <- paste0(colnames(link_data), "_Plantnet")
polplant_original[,28:34] <- link_data[match(polplant_original$ID, link_data$ID_Plantnet),]

# create dataset to validate the results
validate <- polplant_original[!is.na(polplant_original$Score_Plantnet),]
validate$GBIF_Name_Plantnet <-NA
validate$GBIF_Genus_Plantnet <- NA
validate$GBIF_Family_Plantnet <- NA


# take unique species names
names <- unique(validate[, c(30,33,34:37)])

# asign GBIF names
i=1
for(i in 1: length(names$Name_Plantnet)){
  if(is.na(names$GBIF_ID_Plantnet[i])) next
  res <- name_usage( key = names$GBIF_ID_Plantnet[i])
  names$GBIF_Name_Plantnet[i] <- res$data$species
  names$GBIF_Genus_Plantnet[i] <- res$data$genus
  names$GBIF_Family_Plantnet[i] <- res$data$family
}


# look whether these are the accepted names
gbif_plantnet <- name_backbone_checklist(names$GBIF_Name_Plantnet)
# check whether any of these is a synonym
any(gbif_plantnet$status != "ACCEPTED" & !is.na(gbif_plantnet$status))
# assign
validate$GBIF_Name_Plantnet <- names$GBIF_Name_Plantnet[match(validate$Name_Plantnet, names$Name_Plantnet)]
validate$GBIF_Genus_Plantnet <- names$GBIF_Genus_Plantnet[match(validate$Name_Plantnet, names$Name_Plantnet)]
validate$GBIF_Family_Plantnet <- names$GBIF_Family_Plantnet[match(validate$Name_Plantnet, names$Name_Plantnet)]

# check plantnet names of thos not yet 
names <- names[is.na(names$GBIF_Name_Plantnet),]
i=1
# lookup in powo if not in GBIF
powo <- names[!is.na(names$POWO_ID_Plantnet),]
for(i in 1: length(powo$Name_Plantnet)) {
  powo_name <- lookup_powo(powo$POWO_ID_Plantnet[i])
  if(powo_name$taxonomicStatus[i]=="Accepted"){
    names$GBIF_Name_Plantnet[!is.na(names$POWO_ID_Plantnet)][i] <- powo_name$name
    names$GBIF_Genus_Plantnet[!is.na(names$POWO_ID_Plantnet)][i] <- powo_name$genus
    names$GBIF_Family_Plantnet[!is.na(names$POWO_ID_Plantnet)][i] <- powo_name$family

  } 
}

# read names
names_definition <- read_csv("../Extra/Names/plant_names.csv", show_col_types = FALSE)

gbif_plantnet <- name_backbone_checklist(names$Name_Plantnet)

lookup_powo(names$POWO_ID_Plantnet[2])
# look at difference between both columns
none <- name_backbone_checklist(validate$Name_Plantnet[is.na(validate$GBIF_ID_Plantnet)])
none <- cbind(c(validate$ID[is.na(validate$GBIF_ID_Plantnet)]), none)
colnames(none)[1] <- "ID"
i=1
for(i in 1: length(none$usageKey)){
  if(is.na(none$acceptedUsageKey[i])) next
  res <- name_usage( key = none$acceptedUsageKey[i])
  validate$GBIF_Name_Plantnet[validate$ID %in% none$ID[i]] <- res$data$species
  validate$GBIF_Genus_Plantnet[validate$ID %in% none$ID[i]] <- res$data$genus
  validate$GBIF_Family_Plantnet[validate$ID %in% none$ID[i]] <- res$data$family
}

name_usage( key = 3042506)$data
```



## 3.2 scores
```{r}
# Species
# Score >= 0.5
check_score <- validate %>% filter(Score_Plantnet>=0.80) %>% mutate(agree = case_when( powo == Name_Plantnet ~ "yes",TRUE ~ "no"))
nrow(check_score[check_score$agree== "yes",])/nrow(check_score)

# Genus
# Score >= 0.5
check_score <- validate %>% filter(Score_Plantnet>=0.30) %>% mutate(agree = case_when( genus_plants == Genus_Plantnet ~ "yes",TRUE ~ "no"))
nrow(check_score[check_score$agree== "yes",])/nrow(check_score)

# Family
# Score >= 0.5
check_score <- validate %>% filter(Score_Plantnet>=0.0) %>% mutate(agree = case_when( family_plants == Family_Plantnet ~ "yes",TRUE ~ "no"))
nrow(check_score[check_score$agree== "yes",])/nrow(check_score)
```


# POLDATA
# 1 Link
Link with folder
```{r}
image_folder <- "D:/Data Natuurpunt/batch2/batch2"
# Create full paths using the image names
image_files <- file.path(image_folder_b, paste0(pictures_poldata$foto_id, ".jpg")) 
# Filter to include only existing files (avoid errors)
image_files <- image_files_b[file.exists(image_files_b)]

pictures_poldata$url <- image_files[match(file.path(image_folder, paste0(pictures_poldata$foto_id, ".jpg")),image_files)]
# are there any observations without picture
length(pictures_poldata$url[is.na(pictures_poldata$url)])


pictures_poldata$url <- NA
existing_batch2a[existing_batch2a %in% "42510974.jpg"]

existing_batch2a <- list.files(image_folder, full.names = FALSE)
pictures_poldata$url[pictures_poldata$foto_id %in% gsub(".jpg","",existing_batch2a)] <- 
  file.path(image_folder, paste0(pictures_poldata$foto_id[pictures_poldata$foto_id %in% gsub(".jpg","",existing_batch2a)], ".jpg"))

existing_batch2 <- list.files(image_folder_b, full.names = FALSE)
pictures_poldata$url[pictures_poldata$foto_id %in% gsub(".jpg","",existing_batch2)] <- 
  file.path(image_folder_b, paste0(pictures_poldata$foto_id[pictures_poldata$foto_id %in% gsub(".jpg","",existing_batch2)], ".jpg"))



```


# 2 Plantnet
```{r}
result_list <-read_rds("../Results/poldata_identification.RData")
already_identified <- names(result_list)
```


```{r}
# key
api_key <- "2b10bu236VtELMT8bV13UQb73e"

# Set the API endpoint
url <- paste0("https://my-api.plantnet.org/v2/identify/all?api-key=", api_key)

# get pictures per id
id_poldata <- unique(poldata_original$ID[!is.na(poldata_original$PictureID)])
# remove already done
id_poldata <- id_poldata[!id_poldata %in% as.numeric(already_identified)]
# reduce size (for identification)
id_poldata <- id_poldata[1:10]

id = id_poldata[1]

results_list <- list()

for(id in id_poldata){
  
  # get all IDs corresponding to that plant species
  picturesURL_all <- pictures_poldata$url[pictures_poldata$wnm_id %in% id]
  
  
  # Split into chunks of 5 images each (PlantNet limit)
  chunks <- ceiling(length(picturesURL_all)/5)
  
  results_poldata <- data.frame(ID = numeric(),Score = numeric(), Name = character(), Common_name = character(), Name_author= character(),
                                 Genus= character(), Genus_author= character(), Family = character(), Family_author = character(), 
                                 GBIF_ID = character(),POWO_ID = character(), IUCN_ID = character(), IUCN = character())
  
  results_poldata_organs <- data.frame(ID= numeric(),Picture_ID = character(), Organ = character(), Score = numeric() )
  chunk=1
  for (chunk in 1: chunks) {
    length_chunks <- ceiling(length(picturesURL_all)/chunks) 
    # create begin and end values for the plot observation ID
    min_chunk<- ((chunk-1)*length_chunks+1)
    max_chunk<- (chunk*length_chunks)

    if(max_chunk>length(picturesURL_all)){
      max_chunk <- length(picturesURL_all)
    }
      
    picturesURL <- picturesURL_all[min_chunk: max_chunk]
    
    # create body to put images together in the API url
    body <- c(setNames(lapply(picturesURL, upload_file), rep("images", length(picturesURL))),
              setNames(as.list(rep("auto", length(picturesURL))), rep("organs", length(picturesURL))))
    
    # use POST to upload images
    response <- POST(url, body = body, encode = "multipart")
  
    if (response$status_code == 200) {
      # get result from response and make it a table
      result <- content(response, as = "text", encoding = "UTF-8")
  
      # make data frame
      parsed_result <- fromJSON(result, flatten = TRUE)
      # get organ predicted
      predicted_organ <- parsed_result$predictedOrgans[,2:4]
      predicted_organ <- cbind(rep(id, nrow(parsed_result$predictedOrgans)), predicted_organ)
      predicted_organ$filename <- gsub(".jpg","", predicted_organ$filename)
      colnames(predicted_organ) <- c("ID","Picture_ID","Organ","Score")
  
      # get plants predicted and change names
      predicted_plant <- cbind(rep(id, nrow(parsed_result$results)), parsed_result$results)
      if(ncol(predicted_plant)>14){
          predicted_plant <- predicted_plant[, c(1,2,3,5,6,7,9,10,12,13,14,15,16)]
          colnames(predicted_plant) <- c("ID","Score","Name","Common_name","Name_author","Genus","Genus_author","Family","Family_author","GBIF_ID",
                                         "POWO_ID","IUCN_ID","IUCN")
      } else {
          predicted_plant <- predicted_plant[, c(1,2,3,5,6,7,9,10,12,13,14)]
          colnames(predicted_plant) <- c("ID","Score","Name","Common_name","Name_author","Genus","Genus_author","Family","Family_author",
                                         "GBIF_ID","POWO_ID")
      }
      
      # only save the first common name given
      for(com_id in 1: nrow(parsed_result$results)){
        predicted_plant$Common_name[[com_id]] <- as.character(predicted_plant$Common_name[[com_id]][1])
      }
      predicted_plant$Common_name <- as.character(predicted_plant$Common_name)
            
      # Store results in a list (create a data frame for this image)
      
      results_poldata <- bind_rows(results_poldata, predicted_plant)
      results_poldata_organs <- bind_rows(results_poldata_organs, predicted_organ)
      } else {
      add <- data.frame(ID= as.numeric(as.character((id))), Score = as.numeric(NA), Name = NA, Common_name = NA, Name_author= NA,
                                Genus= NA, Genus_author= NA, Family = NA, Family_author = NA, 
                                GBIF_ID = NA, POWO_ID = NA, IUCN_ID = NA, IUCN = NA)
    
      results_poldata <- bind_rows(results_poldata, add)
      add_organs <- data.frame(ID= as.numeric(as.character((id))), Picture_ID = as.character(NA), Organ = NA, Score = NA)
      results_poldata_organs <- bind_rows(results_poldata_organs, add_organs)
      }
    results_list[[as.character(id)]] <- list(predicted_organ = results_poldata_organs, predicted_plant = results_poldata)
  }
  
}

results_list <- c(result_list, results_list)

write_rds(results_list, "../Results/poldata_identification.RData")
```



Retrieve all with highest scores
```{r}
# create empty data frame to paste most likely results in
poldata_plantnet <- data.frame(ID = numeric(),Score = numeric(), Name = character(), Common_name = character(), Name_author= character(),
                                Genus= character(), Genus_author= character(), Family = character(), Family_author = character(), 
                                GBIF_ID = character(),POWO_ID = character(), IUCN_ID = character(), IUCN = character(), Identification = character())

id_poldata <- as.numeric(names(results_list))

# create final dataset from the list 
for(id in id_poldata){
  # predicted data for that observation ID
  predicted <-   results_list[[as.character(id)]]
  if(all(is.na(predicted$predicted_organ$Organ))){
    add <- data.frame(ID= as.numeric(as.character((id))), Score = as.numeric(NA), Name = NA, Common_name = NA, Name_author= NA,
                                Genus= NA, Genus_author= NA, Family = NA, Family_author = NA, 
                                GBIF_ID = NA, POWO_ID = NA, IUCN_ID = NA, IUCN = NA, Identification = "None")
    
    poldata_plantnet <- bind_rows(poldata_plantnet, add)
  } else if(any(predicted$predicted_organ$Organ[!is.na(predicted$predicted_organ$Organ)] == "flower")){
    poldata_plantnet <- bind_rows(poldata_plantnet, c(predicted$predicted_plant[which.max(predicted$predicted_plant$Score),], Identification ="Flower"))
  } else {
    organ_identified <- names(sort(table(predicted$predicted_organ$Organ), decreasing=TRUE)[1])
    poldata_plantnet <- bind_rows(poldata_plantnet, c(predicted$predicted_plant[which.max(predicted$predicted_plant$Score),], Identification ="Flower"))
  }
}

check_picture_id <- pictures_poldata$foto_id[pictures_poldata$wnm_id %in% poldata_plantnet$ID[is.na(poldata_plantnet$Name)]]

identified_picture_id  <- pictures_poldata$foto_id[pictures_poldata$wnm_id %in% poldata_plantnet$ID[!is.na(poldata_plantnet$Name)]]
```